version: '3.7'
services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    # networks:
    #   net:
    #     ipv4_address: 172.26.13.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ~:/mnt

# networks:
#   net:
#     driver: bridge
#     ipam:
#      config:
#        - subnet: 172.26.13.5/16
#          gateway: 172.26.13.5

volumes:
  mongodb_data_container:
