version: "2.3"
services:
  pg:
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
    network_mode: 'host'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    network_mode: 'host'
